# Generated by Django 4.2.3 on 2025-02-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Statement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("GAS_LEAK", "Gas Leak"),
                    ("METER_ISSUE", "Meter Issue"),
                    ("BILLING", "Billing Issue"),
                    ("OTHER", "Other"),
                ],
                max_length=23,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
