# Generated by Django 4.2.3 on 2025-02-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Statement", "0002_remove_customer_address_customer_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
