# Generated by Django 4.2.3 on 2025-02-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Statement", "0003_remove_customer_user_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="resolved_date",
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
