# Generated by Django 4.2.3 on 2025-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Statement", "0004_alter_servicerequest_resolved_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="resolved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
