# Generated by Django 4.2.3 on 2025-02-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Statement", "0006_alter_servicerequest_resolved_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequest",
            name="resolved_date",
        ),
    ]
