# Generated by Django 4.2.3 on 2025-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Statement", "0007_remove_servicerequest_resolved_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="resolved_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
